import createMdx from "@next/mdx";
import type { NextConfig } from "next";

/** The slice of webpack's config this file touches. Narrow, so nothing here is `any`. */
interface WebpackConfig {
  resolve?: {
    extensionAlias?: Record<string, string[]>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/**
 * docs/11 §Security pins the response headers; docs/08 §"Design principles" pins the rest.
 *
 * `typedRoutes` is on because a route typo that only shows up as a 404 in staging is exactly the
 * class of bug a typed codebase should not have.
 */
const securityHeaders = [
  // docs/11 §Security: "Strict CSP (`default-src 'self'`), HSTS, `X-Content-Type-Options`,
  // `Referrer-Policy`."
  //
  // The CSP itself is *not* here: it carries a per-request nonce, and a static header cannot.
  // `src/middleware.ts` sets it. These four are request-independent and belong at the edge.
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Frame-Options", value: "DENY" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
];

/**
 * MDX, for the blog and the legal documents (Prompt 18 §2 and §3).
 *
 * `docs/02` locks no content layer — it is silent on the blog beyond noting that "pricing, blog,
 * instrument pages are exactly the kind of long-tail SEO surface" SSR exists for. Prompt 18 names
 * MDX explicitly, so `@next/mdx` is the Next-native answer and adds no runtime to the client
 * bundle: MDX compiles to React server components at build time. `docs/DECISIONS.md` §18.1.
 *
 * No remark or rehype plugins. A plugin chain is a second thing that can break a build, and
 * neither the four legal documents nor the three posts need one.
 */
const withMdx = createMdx({});

const nextConfig: NextConfig = {
  reactStrictMode: true,
  /* `.mdx` is only a *page* extension for completeness; every MDX file in this repo is imported
     as a component from a `.tsx` route, so the content and the route metadata stay apart. */
  pageExtensions: ["ts", "tsx", "mdx"],
  /*
   * `@decile/api-client` ships TypeScript source, not a build artefact: it is generated from
   * `openapi.json` and regenerated by CI, and a compiled `dist/` would be a second thing to keep
   * in step. Next compiles it as part of this app instead.
   */
  transpilePackages: ["@decile/api-client"],
  typedRoutes: true,
  poweredByHeader: false,
  eslint: {
    // `pnpm run lint` runs eslint explicitly; running it again inside `next build` doubles the
    // work and hides failures behind a build log.
    ignoreDuringBuilds: true,
  },
  /*
   * The package's own imports are written with the `.js` extensions that NodeNext resolution
   * requires of ESM. The files on disk are `.ts`, so webpack is told the mapping explicitly.
   */
  webpack(config: WebpackConfig): WebpackConfig {
    const resolve = config.resolve ?? {};
    return {
      ...config,
      resolve: {
        ...resolve,
        extensionAlias: { ...resolve.extensionAlias, ".js": [".ts", ".tsx", ".js"] },
      },
    };
  },
  headers() {
    return Promise.resolve([{ source: "/:path*", headers: securityHeaders }]);
  },
};

export default withMdx(nextConfig);
