"""Initial schema — every table in docs/04-data-model.md.

Adds, on top of what autogenerate produces from the models:
  * the ``timescaledb`` and ``citext`` extensions (docs/04; ``app_user.email`` is citext);
  * the three hypertables — ``ohlcv_daily``, ``factor_daily``, ``index_member_daily`` — each
    partitioned on ``date`` in 1-year chunks, exactly as docs/04 specifies;
  * the ``ohlcv_daily`` compression policy (compress after 90 days, segment by instrument_id).

``factor_daily`` is deliberately left uncompressed: docs/04 §"Retention & size estimates" says to
keep it uncompressed for 2 years, and it states no policy DDL, so none is created here.

Downgrade drops the tables (which takes their hypertables and policies with them) but does NOT
drop the extensions: ``DROP EXTENSION timescaledb`` is destructive to anything else in the
database, and an extension is not this migration's to remove.


Revision ID: 0001_initial
Revises:
Create Date: 2026-08-20 03:30:33.436588
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- Extensions (docs/04) ----------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
        sa.UniqueConstraint("public_id", name=op.f("uq_app_user_public_id")),
    )
    op.create_table(
        "exchange",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange")),
        sa.UniqueConstraint("code", name=op.f("uq_exchange_code")),
    )
    op.create_table(
        "index_def",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_universe", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_def")),
        sa.UniqueConstraint("slug", name=op.f("uq_index_def_slug")),
    )
    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_version", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run")),
    )
    op.create_table(
        "plan",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("price_inr", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("interval", sa.String(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "interval IS NULL OR interval IN ('month', 'year')", name=op.f("ck_plan_plan_interval")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
        sa.UniqueConstraint("code", name=op.f("uq_plan_code")),
    )
    op.create_table(
        "index_snapshot_daily",
        sa.Column("index_id", sa.SmallInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("level", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("change_abs", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("change_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("pe", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("pb", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("div_yield", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_id"], ["index_def.id"], name=op.f("fk_index_snapshot_daily_index_id_index_def")
        ),
        sa.PrimaryKeyConstraint("index_id", "date", name=op.f("pk_index_snapshot_daily")),
    )
    op.create_table(
        "instrument",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("exchange_id", sa.SmallInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("instrument_type", sa.String(), nullable=False),
        sa.Column("series", sa.String(), nullable=True),
        sa.Column("face_value", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("delisted_on", sa.Date(), nullable=True),
        sa.Column("kite_token", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "instrument_type IN ('EQ', 'ETF', 'INDEX')",
            name=op.f("ck_instrument_instrument_type_known"),
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchange.id"], name=op.f("fk_instrument_exchange_id_exchange")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
        sa.UniqueConstraint(
            "exchange_id", "symbol", "series", name=op.f("uq_instrument_exchange_id_symbol_series")
        ),
    )
    op.create_index("ix_instrument_kite_token", "instrument", ["kite_token"], unique=False)
    op.create_index("ix_instrument_symbol", "instrument", ["symbol"], unique=False)
    op.create_table(
        "market_health_daily",
        sa.Column("index_id", sa.SmallInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("pct_above_200dma", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("pct_above_50dma", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("pct_within_10pct_ath", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("pct_ret_1y_positive", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("constituent_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_id"], ["index_def.id"], name=op.f("fk_market_health_daily_index_id_index_def")
        ),
        sa.PrimaryKeyConstraint("index_id", "date", name=op.f("pk_market_health_daily")),
    )
    op.create_table(
        "pipeline_run_step",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("step", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rows_in", sa.BigInteger(), nullable=True),
        sa.Column("rows_out", sa.BigInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_run.id"],
            name=op.f("fk_pipeline_run_step_run_id_pipeline_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run_step")),
    )
    op.create_table(
        "portfolio",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_portfolio_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio")),
    )
    op.create_table(
        "screen",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "columns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_example", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_screen_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screen")),
        sa.UniqueConstraint("public_id", name=op.f("uq_screen_public_id")),
    )
    op.create_index("ix_screen_user_id", "screen", ["user_id"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("razorpay_subscription_id", sa.String(), nullable=True),
        sa.Column("razorpay_customer_id", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'past_due', 'cancelled', 'expired')",
            name=op.f("ck_subscription_subscription_status"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plan.id"], name=op.f("fk_subscription_plan_id_plan")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_subscription_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
    )
    op.create_table(
        "trading_day",
        sa.Column("exchange_id", sa.SmallInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_trading_day", sa.Boolean(), nullable=False),
        sa.Column("holiday_name", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.CheckConstraint(
            "source IN ('weekend', 'holiday', 'derived', 'bhavcopy')",
            name=op.f("ck_trading_day_trading_day_source"),
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchange.id"], name=op.f("fk_trading_day_exchange_id_exchange")
        ),
        sa.PrimaryKeyConstraint("exchange_id", "date", name=op.f("pk_trading_day")),
    )
    op.create_index(
        "ix_trading_day_is_trading_day_date",
        "trading_day",
        ["is_trading_day", "date"],
        unique=False,
    )
    op.create_table(
        "backtest",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("screen_id", sa.BigInteger(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("equity_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trades_key", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')",
            name=op.f("ck_backtest_backtest_status"),
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"], ["screen.id"], name=op.f("fk_backtest_screen_id_screen")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_backtest_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest")),
        sa.UniqueConstraint("public_id", name=op.f("uq_backtest_public_id")),
    )
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("ratio_from", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("ratio_to", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "action_type IN ('dividend', 'split', 'bonus', 'rights', 'demerger')",
            name=op.f("ck_corporate_action_corporate_action_type"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_corporate_action_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_action")),
        sa.UniqueConstraint(
            "instrument_id",
            "action_type",
            "ex_date",
            name=op.f("uq_corporate_action_instrument_id_action_type_ex_date"),
        ),
    )
    op.create_table(
        "factor_daily",
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("close_raw", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ret_1m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_3m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_6m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_9m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_12m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_12m_minus_1m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ret_12m_minus_2m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("vol_1m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("vol_3m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("vol_6m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("vol_9m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("vol_12m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("sharpe_1m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sharpe_3m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sharpe_6m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sharpe_9m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("sharpe_12m", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rsi_1m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("rsi_3m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("rsi_6m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("rsi_9m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("rsi_12m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("beta_12m", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("ma_20", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ma_50", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ma_100", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ma_200", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("high_1y", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("high_ath", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("away_high_1y", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("away_high_ath", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pos_days_1m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("pos_days_3m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("pos_days_6m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("pos_days_9m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("pos_days_12m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("circuits_1m", sa.SmallInteger(), nullable=True),
        sa.Column("circuits_3m", sa.SmallInteger(), nullable=True),
        sa.Column("circuits_6m", sa.SmallInteger(), nullable=True),
        sa.Column("circuits_9m", sa.SmallInteger(), nullable=True),
        sa.Column("circuits_12m", sa.SmallInteger(), nullable=True),
        sa.Column("vol_day_val", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_1w", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_1m", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_3m", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_6m", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_9m", sa.BigInteger(), nullable=True),
        sa.Column("vol_avg_12m", sa.BigInteger(), nullable=True),
        sa.Column("median_vol_12m", sa.BigInteger(), nullable=True),
        sa.Column("marketcap_cr", sa.BigInteger(), nullable=True),
        sa.Column("pe", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("series", sa.String(), nullable=True),
        sa.Column("regime", sa.String(), nullable=True),
        sa.Column("universe_mask", sa.Integer(), server_default="0", nullable=False),
        sa.Column("top_beta_mask", sa.Integer(), server_default="0", nullable=False),
        sa.Column("top_volatility_mask", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_factor_daily_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date", name=op.f("pk_factor_daily")),
    )
    op.create_index("ix_factor_daily_date", "factor_daily", ["date"], unique=False)
    op.create_index(
        "ix_factor_daily_date_marketcap_cr",
        "factor_daily",
        ["date", "marketcap_cr"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "fundamental_daily",
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("marketcap_cr", sa.BigInteger(), nullable=True),
        sa.Column("pe", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("pb", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("div_yield", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("shares_outstanding", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_fundamental_daily_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date", name=op.f("pk_fundamental_daily")),
    )
    op.create_table(
        "index_member_daily",
        sa.Column("index_id", sa.SmallInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_id"], ["index_def.id"], name=op.f("fk_index_member_daily_index_id_index_def")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_index_member_daily_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint(
            "index_id", "date", "instrument_id", name=op.f("pk_index_member_daily")
        ),
    )
    op.create_index(
        "ix_index_member_daily_date_index_id",
        "index_member_daily",
        ["date", "index_id"],
        unique=False,
    )
    op.create_table(
        "ohlcv_daily",
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("close_raw", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("volume_raw", sa.BigInteger(), nullable=False),
        sa.Column("turnover", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "adj_factor", sa.Numeric(precision=18, scale=10), server_default="1", nullable=False
        ),
        sa.Column("upper_circuit", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("lower_circuit", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.CheckConstraint(
            "source IN ('kite', 'nse')", name=op.f("ck_ohlcv_daily_ohlcv_daily_source")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_ohlcv_daily_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("instrument_id", "date", name=op.f("pk_ohlcv_daily")),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=True),
        sa.Column("amount_inr", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gst_inr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("razorpay_payment_id", sa.String(), nullable=True),
        sa.Column("invoice_number", sa.String(), nullable=True),
        sa.Column("invoice_pdf_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscription.id"],
            name=op.f("fk_payment_subscription_id_subscription"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_payment_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_payment_invoice_number")),
        sa.UniqueConstraint("razorpay_payment_id", name=op.f("uq_payment_razorpay_payment_id")),
    )
    op.create_table(
        "portfolio_holding",
        sa.Column("portfolio_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("avg_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("added_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_portfolio_holding_instrument_id_instrument"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("fk_portfolio_holding_portfolio_id_portfolio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "instrument_id", name=op.f("pk_portfolio_holding")),
    )
    op.create_table(
        "screen_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("definition_hash", sa.String(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"],
            ["screen.id"],
            name=op.f("fk_screen_run_screen_id_screen"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screen_run")),
        sa.UniqueConstraint(
            "screen_id",
            "as_of",
            "definition_hash",
            name=op.f("uq_screen_run_screen_id_as_of_definition_hash"),
        ),
    )
    op.create_table(
        "symbol_alias",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("old_symbol", sa.String(), nullable=False),
        sa.Column("changed_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_symbol_alias_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_alias")),
    )

    # --- TimescaleDB hypertables (docs/04) ---------------------------------
    # `migrate_data => true` is not needed: these tables were created empty moments ago.
    for table in ("ohlcv_daily", "factor_daily", "index_member_daily"):
        op.execute(
            f"SELECT create_hypertable('{table}', 'date', chunk_time_interval => INTERVAL '1 year')"
        )

    # --- Compression policy for ohlcv_daily (docs/04) -----------------------
    op.execute(
        "ALTER TABLE ohlcv_daily SET ("
        "timescaledb.compress, timescaledb.compress_segmentby = 'instrument_id')"
    )
    op.execute("SELECT add_compression_policy('ohlcv_daily', INTERVAL '90 days')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("symbol_alias")
    op.drop_table("screen_run")
    op.drop_table("portfolio_holding")
    op.drop_table("payment")
    op.drop_table("ohlcv_daily")
    op.drop_index("ix_index_member_daily_date_index_id", table_name="index_member_daily")
    op.drop_table("index_member_daily")
    op.drop_table("fundamental_daily")
    op.drop_index(
        "ix_factor_daily_date_marketcap_cr", table_name="factor_daily", postgresql_using="btree"
    )
    op.drop_index("ix_factor_daily_date", table_name="factor_daily")
    op.drop_table("factor_daily")
    op.drop_table("corporate_action")
    op.drop_table("backtest")
    op.drop_index("ix_trading_day_is_trading_day_date", table_name="trading_day")
    op.drop_table("trading_day")
    op.drop_table("subscription")
    op.drop_index("ix_screen_user_id", table_name="screen")
    op.drop_table("screen")
    op.drop_table("portfolio")
    op.drop_table("pipeline_run_step")
    op.drop_table("market_health_daily")
    op.drop_index("ix_instrument_symbol", table_name="instrument")
    op.drop_index("ix_instrument_kite_token", table_name="instrument")
    op.drop_table("instrument")
    op.drop_table("index_snapshot_daily")
    op.drop_table("plan")
    op.drop_table("pipeline_run")
    op.drop_table("index_def")
    op.drop_table("exchange")
    op.drop_table("app_user")
    # ### end Alembic commands ###
