"""ingest_cursor — the resumable-backfill cursor (Prompt 3 deliverable 6).

Not a table in docs/04; see docs/04b-ingest-cursor-addendum.md for its rationale and shape.


Revision ID: 0002_ingest_cursor
Revises: 0001_initial
Create Date: 2026-08-20 05:02:27.081581
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_ingest_cursor"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_cursor",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rows_written", sa.BigInteger(), nullable=True),
        sa.Column("attempts", sa.BigInteger(), nullable=False),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'done', 'failed')",
            name=op.f("ck_ingest_cursor_ingest_cursor_status"),
        ),
        sa.CheckConstraint(
            "window_end >= window_start", name=op.f("ck_ingest_cursor_ingest_cursor_window_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_ingest_cursor_instrument_id_instrument"),
        ),
        sa.PrimaryKeyConstraint(
            "kind", "instrument_id", "window_start", name=op.f("pk_ingest_cursor")
        ),
    )
    op.create_index(
        "ix_ingest_cursor_kind_status", "ingest_cursor", ["kind", "status"], unique=False
    )
    op.drop_index(op.f("index_member_daily_date_idx"), table_name="index_member_daily")
    op.drop_index(op.f("ohlcv_daily_date_idx"), table_name="ohlcv_daily")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ohlcv_daily_date_idx"), "ohlcv_daily", [sa.literal_column("date DESC")], unique=False
    )
    op.create_index(
        op.f("index_member_daily_date_idx"),
        "index_member_daily",
        [sa.literal_column("date DESC")],
        unique=False,
    )
    op.drop_index("ix_ingest_cursor_kind_status", table_name="ingest_cursor")
    op.drop_table("ingest_cursor")
    # ### end Alembic commands ###
