"""UNIQUE (run_id, step) on pipeline_run_step.

An addition to docs/04's DDL. Prompt 3 deliverable 2 requires each task to upsert its
pipeline_run_step row rather than blind-insert; without this constraint a re-run appends a second,
contradictory record for the same step.


Revision ID: 0003_unique_pipeline_run_step
Revises: 0002_ingest_cursor
Create Date: 2026-08-20 05:04:43.589274
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0003_unique_pipeline_run_step"
down_revision: str | None = "0002_ingest_cursor"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_pipeline_run_step_run_id_step"), "pipeline_run_step", ["run_id", "step"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_pipeline_run_step_run_id_step"), "pipeline_run_step", type_="unique"
    )
    # ### end Alembic commands ###
