#!/usr/bin/env python
"""Load the research export into the shapes ``baskfy_core.vbt`` expects (VB2).

    cd decile-blueprint
    uv run python ../tools/vbt/reproduce.py

``research/volume-breakout/aws/`` is the read-only export of the AWS Phase-A box's tables as of
10 September 2026 — 3.75 M bars over 4,186 traded instruments, 2017-01-02 → 2026-09-09. It is
**gitignored** (68 MB) and is regenerated by ``research/volume-breakout/export_bars_aws.sh``.
Nothing here writes to it, and nothing here reaches a network or a database.

This module exists so that VB2's reproduction and VB9's plant run differ only in *where the bars
came from*: both hand ``baskfy_core.vbt`` the same frame shape, so a difference between them is a
difference in the data and never in the loader.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import polars as pl

from baskfy_core.vbt.calendar import SessionCalendar, drop_thin_sessions
from baskfy_core.vbt.config import DEFAULT_VBT_CONFIG, VbtConfig

#: Where the export lives, relative to the repository root.
EXPORT = Path(__file__).resolve().parents[2] / "research" / "volume-breakout" / "aws"
#: Where the study's own answers live, for the comparison VB2 is.
RESULTS = Path(__file__).resolve().parents[2] / "research" / "volume-breakout" / "out"


@dataclass(frozen=True, slots=True)
class LoadedPanel:
    bars: pl.DataFrame
    calendar: SessionCalendar
    universe: pl.DataFrame
    dropped_sessions: tuple[object, ...]


def _read(name: str, directory: Path = EXPORT) -> pl.DataFrame:
    for candidate in (directory / f"{name}.csv.gz", directory / f"{name}.csv"):
        if candidate.exists():
            return pl.read_csv(candidate, infer_schema_length=10_000)
    raise FileNotFoundError(
        f"{name} is not in {directory}. The export is gitignored (68 MB); regenerate it with "
        "research/volume-breakout/export_bars_aws.sh, which reads the AWS box over SSM."
    )


def etf_instrument_ids(directory: Path = EXPORT) -> set[int]:
    """The ``etf`` universe's members. The regexes in ``04`` §1 only catch what it missed."""
    try:
        definitions = _read("index_def", directory)
        members = _read("index_member_daily", directory)
    except FileNotFoundError:
        return set()
    slug = DEFAULT_VBT_CONFIG.data.etf_universe_slug
    index_ids = definitions.filter(pl.col("slug") == slug)["id"].to_list()
    if not index_ids:
        return set()
    return set(members.filter(pl.col("index_id").is_in(index_ids))["instrument_id"].to_list())


def universe(config: VbtConfig = DEFAULT_VBT_CONFIG, directory: Path = EXPORT) -> pl.DataFrame:
    """``(id, symbol)`` for every name ``04`` §1 admits: NSE cash, EQ/BE/BZ, no ETFs, no SME."""
    data = config.data
    frame = _read("instrument", directory).filter(
        pl.col("instrument_type") == data.instrument_type
    )
    series = pl.col("series").fill_null("EQ" if data.keep_null_series else "")
    frame = frame.with_columns(series.alias("series")).filter(
        pl.col("series").is_in(list(data.series_allowed))
    )
    etf_ids = etf_instrument_ids(directory)
    name_pattern = re.compile(data.etf_name_pattern, re.IGNORECASE)
    symbol_pattern = re.compile(data.etf_symbol_pattern, re.IGNORECASE)
    keep = [
        record["id"] not in etf_ids
        and not name_pattern.search(record["name"] or "")
        and not symbol_pattern.search(record["symbol"])
        for record in frame.iter_rows(named=True)
    ]
    return frame.filter(pl.Series(keep)).select(
        pl.col("id").alias("instrument_id"), "symbol", "name", "series"
    )


def load(
    config: VbtConfig = DEFAULT_VBT_CONFIG,
    directory: Path = EXPORT,
    *,
    start: str | None = None,
    end: str | None = None,
) -> LoadedPanel:
    """The bars of the ``04`` §1 universe, on the ``04`` §2 calendar."""
    names = universe(config, directory)
    bars = _read("ohlcv_daily", directory).with_columns(pl.col("date").str.to_date())
    if start:
        bars = bars.filter(pl.col("date") >= pl.lit(start).str.to_date())
    if end:
        bars = bars.filter(pl.col("date") <= pl.lit(end).str.to_date())
    bars = bars.join(names.select("instrument_id", "symbol"), on="instrument_id", how="inner")
    columns = [
        "instrument_id",
        "symbol",
        "date",
        "open",
        "high",
        "low",
        "close",
        "close_raw",
        "volume",
    ]
    for optional in ("upper_circuit", "adj_factor"):
        if optional in bars.columns:
            columns.append(optional)
    bars = bars.select(columns)
    kept, calendar = drop_thin_sessions(bars, config)
    return LoadedPanel(
        bars=kept,
        calendar=calendar,
        universe=names,
        dropped_sessions=calendar.dropped,
    )
