"""FixtureProvider — both ports, served from Parquet, zero network (Prompt 2 deliverable 5).

docs/09's table: "``FixtureProvider`` — local dev/tests; reads Parquet fixtures, zero network."
docs/03 §Environments: the ``local`` environment is a sample universe "seeded from fixtures",
with "no Kite calls, provider stubbed".

It implements ``BarsProvider`` *and* ``ReferenceProvider``, so a local stack or a test can wire
one object where production wires a CompositeProvider over two vendors, and every call site is
identical.

The data is generated by ``baskfy_providers.fixture_builder``; see ``PROVENANCE.md`` next to the
Parquet files for exactly which parts are real and which are synthetic.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Mapping, Sequence
from decimal import Decimal
from functools import cached_property
from pathlib import Path
from typing import Final

import polars as pl

from baskfy_providers.errors import ProviderUnavailable, UnexpectedPayload
from baskfy_providers.ports import (
    BARS_CAPABILITIES,
    HOLDINGS_CAPABILITIES,
    REFERENCE_CAPABILITIES,
    Capability,
    ProviderHealth,
)
from baskfy_providers.records import (
    BHAVCOPY_SCHEMA,
    DAILY_BARS_SCHEMA,
    BrokerAccountRef,
    BrokerHoldingRecord,
    CorporateAction,
    EquityFundamental,
    IndexSnapshot,
    InstrumentRecord,
    ListingRecord,
    conform,
    empty_frame,
)

PROVIDER_NAME: Final = "fixture"

#: Deliberately a *different* name from ``FixtureProvider``. ``CompositeProvider`` refuses two
#: adapters with the same name, and more to the point every log line, health report and error
#: message that mentions invented holdings should say so in its own words.
HOLDINGS_PROVIDER_NAME: Final = "fixture-holdings"

_FILES: Final[dict[str, str]] = {
    "instruments": "instruments.parquet",
    "daily_bars": "daily_bars.parquet",
    "corporate_actions": "corporate_actions.parquet",
    "index_members": "index_members.parquet",
    "index_snapshots": "index_snapshots.parquet",
    "listings": "listings.parquet",
    "bhavcopy": "bhavcopy.parquet",
}


def default_fixture_dir() -> Path:
    """``tests/fixtures/providers``, located from this file."""
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "tests" / "fixtures" / "providers"
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError("no tests/fixtures/providers directory found above this file")


class FixtureProvider:
    """Serves both provider ports from the Parquet fixtures."""

    def __init__(self, fixture_dir: Path | str | None = None) -> None:
        self._dir = Path(fixture_dir) if fixture_dir else default_fixture_dir()

    @property
    def directory(self) -> Path:
        return self._dir

    # --- HealthReporting ------------------------------------------------

    @property
    def name(self) -> str:
        return PROVIDER_NAME

    def capabilities(self) -> frozenset[Capability]:
        """Everything — which is what makes it a drop-in for the whole composite locally."""
        return BARS_CAPABILITIES | REFERENCE_CAPABILITIES

    def check(self) -> ProviderHealth:
        missing = [
            name for name, filename in _FILES.items() if not (self._dir / filename).is_file()
        ]
        if missing:
            return ProviderHealth(
                name=self.name,
                available=False,
                capabilities=self.capabilities(),
                detail=(
                    f"missing fixture files {missing} in {self._dir}; "
                    "regenerate with `python -m baskfy_providers.fixture_builder`"
                ),
            )
        instruments = self._frame("instruments").height
        days = self._frame("daily_bars")["date"].n_unique()
        return ProviderHealth(
            name=self.name,
            available=True,
            capabilities=self.capabilities(),
            detail=f"{instruments} instruments over {days} trading days from {self._dir}",
        )

    # --- BarsProvider ---------------------------------------------------

    def list_instruments(self) -> list[InstrumentRecord]:
        frame = self._frame("instruments")
        return [
            InstrumentRecord(
                symbol=str(row["symbol"]),
                name=str(row["name"]),
                instrument_type=str(row["instrument_type"]),
                series=_text(row.get("series")),
                isin=_text(row.get("isin")),
                exchange=str(row.get("exchange") or "NSE"),
                kite_token=_int(row.get("kite_token")),
                lot_size=_int(row.get("lot_size")),
                listed_on=_date(row.get("listed_on")),
            )
            for row in frame.iter_rows(named=True)
        ]

    def daily_bars(self, token: int, start: dt.date, end: dt.date) -> pl.DataFrame:
        """Bars for the instrument carrying ``token``, addressed exactly as Kite would be."""
        if end < start:
            raise ValueError(f"end {end} precedes start {start}")
        symbol = self._symbol_for_token(token)
        frame = self._frame("daily_bars").filter(
            (pl.col("symbol") == symbol) & (pl.col("date") >= start) & (pl.col("date") <= end)
        )
        if frame.height == 0:
            return empty_frame(DAILY_BARS_SCHEMA)
        return conform(frame.sort("date"), DAILY_BARS_SCHEMA)

    def daily_bars_for_symbol(self, symbol: str, start: dt.date, end: dt.date) -> pl.DataFrame:
        """Convenience for seeding and tests, which think in symbols rather than broker tokens."""
        return self.daily_bars(self._token_for_symbol(symbol), start, end)

    # --- ReferenceProvider ----------------------------------------------

    def index_constituents(self, index_slug: str, on: dt.date) -> list[str]:
        frame = self._frame("index_members").filter(
            (pl.col("index_slug") == index_slug) & (pl.col("date") == on)
        )
        return sorted(str(v) for v in frame["symbol"].to_list())

    def index_snapshots(self, on: dt.date) -> list[IndexSnapshot]:
        frame = self._frame("index_snapshots").filter(pl.col("date") == on)
        return [
            IndexSnapshot(
                index_slug=str(row["index_slug"]),
                date=on,
                level=_decimal(row.get("level")),
                change_abs=_decimal(row.get("change_abs")),
                change_pct=_decimal(row.get("change_pct")),
                pe=_decimal(row.get("pe")),
                pb=_decimal(row.get("pb")),
                div_yield=_decimal(row.get("div_yield")),
            )
            for row in frame.iter_rows(named=True)
        ]

    def corporate_actions(self, since: dt.date) -> list[CorporateAction]:
        frame = self._frame("corporate_actions").filter(pl.col("ex_date") >= since)
        return [
            CorporateAction(
                symbol=str(row["symbol"]),
                action_type=str(row["action_type"]),
                ex_date=_require_date(row["ex_date"], "ex_date"),
                ratio_from=_decimal(row.get("ratio_from")),
                ratio_to=_decimal(row.get("ratio_to")),
                amount=_decimal(row.get("amount")),
                raw={
                    "purpose": str(row.get("purpose") or ""),
                    "provenance": str(row.get("provenance") or ""),
                },
            )
            for row in frame.sort(["symbol", "ex_date"]).iter_rows(named=True)
        ]

    def listings(self) -> list[ListingRecord]:
        frame = self._frame("listings")
        return [
            ListingRecord(
                symbol=str(row["symbol"]),
                name=str(row["name"]),
                series=_text(row.get("series")),
                isin=_text(row.get("isin")),
                listed_on=_date(row.get("listed_on")),
                face_value=_decimal(row.get("face_value")),
                paid_up_value=_decimal(row.get("paid_up_value")),
                market_lot=_int(row.get("market_lot")),
            )
            for row in frame.iter_rows(named=True)
        ]

    def sme_listings(self) -> list[ListingRecord]:
        """The local fixture set is a main-board sample (docs/03 §Environments), so it carries
        no Emerge register. Empty, not absent: the pipeline step must see "no SME rows today"
        rather than "this provider cannot do SME"."""
        return []

    def bhavcopy(self, on: dt.date) -> pl.DataFrame:
        frame = self._frame("bhavcopy").filter(pl.col("date") == on)
        if frame.height == 0:
            return empty_frame(BHAVCOPY_SCHEMA)
        return conform(frame.sort("symbol"), BHAVCOPY_SCHEMA)

    def equity_fundamentals(
        self,
        on: dt.date,
        symbols: Sequence[str],
        *,
        series_by_symbol: Mapping[str, str] | None = None,
    ) -> list[EquityFundamental]:
        """Fixtures carry no issued-capital series. NULL is the honest local-dev answer."""
        del on, symbols, series_by_symbol
        return []

    # --- internals ------------------------------------------------------

    @cached_property
    def _token_map(self) -> dict[int, str]:
        frame = self._frame("instruments")
        return {
            int(row["kite_token"]): str(row["symbol"])
            for row in frame.iter_rows(named=True)
            if row.get("kite_token") is not None
        }

    def _symbol_for_token(self, token: int) -> str:
        try:
            return self._token_map[token]
        except KeyError as exc:
            raise UnexpectedPayload(
                f"no fixture instrument carries kite_token {token}", provider=self.name
            ) from exc

    def _token_for_symbol(self, symbol: str) -> int:
        for token, mapped in self._token_map.items():
            if mapped == symbol:
                return token
        raise UnexpectedPayload(f"no fixture instrument named {symbol!r}", provider=self.name)

    def _frame(self, name: str) -> pl.DataFrame:
        path = self._dir / _FILES[name]
        if not path.is_file():
            raise ProviderUnavailable(
                f"fixture {path} is missing; regenerate with "
                "`python -m baskfy_providers.fixture_builder`",
                provider=self.name,
            )
        return _load(path)


def _load(path: Path) -> pl.DataFrame:
    """Read a fixture. Cached per path+mtime so repeated calls in a test are cheap."""
    return _read_cached(str(path), path.stat().st_mtime_ns)


_CACHE: dict[tuple[str, int], pl.DataFrame] = {}


def _read_cached(path: str, mtime_ns: int) -> pl.DataFrame:
    key = (path, mtime_ns)
    cached = _CACHE.get(key)
    if cached is None:
        cached = pl.read_parquet(path)
        _CACHE[key] = cached
    return cached


def _text(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _int(value: object) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, (int, float, Decimal)):
        return int(value)
    if isinstance(value, str):
        return int(float(value))
    return None


def _decimal(value: object) -> Decimal | None:
    if value is None:
        return None
    if isinstance(value, Decimal):
        return value
    if isinstance(value, (int, float, str)):
        return Decimal(str(value))
    return None


def _date(value: object) -> dt.date | None:
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    if isinstance(value, str):
        return dt.date.fromisoformat(value)
    return None


def _require_date(value: object, field: str) -> dt.date:
    parsed = _date(value)
    if parsed is None:
        raise UnexpectedPayload(f"fixture row has no {field}", provider=PROVIDER_NAME)
    return parsed


class FixtureHoldingsProvider:
    """``HoldingsProvider`` served from rows the caller supplies. Zero network, zero disk.

    WHY THIS IS A SEPARATE CLASS AND NOT A METHOD ON ``FixtureProvider``
    -------------------------------------------------------------------
    ``FixtureProvider`` sits at the back of the production stack (see
    ``factory.build_provider_stack``), where its whole job is to answer when the real vendors
    could not — invented candles for a symbol are a local-development convenience and a wrong
    chart at worst. Holdings are not that. Tree-5's leaf C1 exists because the API labelled a
    genuine live Kite fetch "fixture holdings" and told a user their real money was fake; the
    mirror-image failure, serving invented positions as if they were real, is worse and is the
    one a registered fallback would cause.

    So this adapter is a separate object that the production factory deliberately does **not**
    register. A holdings call with no working broker session fails loudly with
    ``CapabilityNotAvailable`` — the same reasoning ``CompositeProvider`` already applies to
    ``AccessTokenExpired``, for the same reason: wrong numbers that look right are the worst
    failure this repository can have.

    Rows are keyed by ``broker_account_id`` because that is what a
    :class:`~baskfy_providers.records.BrokerAccountRef` names, and because a test that wants to
    prove per-tenant isolation needs two accounts to be two different answers.
    """

    def __init__(
        self,
        holdings: Mapping[int, Sequence[BrokerHoldingRecord]],
        cash: Mapping[int, Decimal] | None = None,
    ) -> None:
        self._holdings = {account_id: tuple(rows) for account_id, rows in holdings.items()}
        self._cash = dict(cash or {})

    # --- HealthReporting ------------------------------------------------

    @property
    def name(self) -> str:
        return HOLDINGS_PROVIDER_NAME

    def capabilities(self) -> frozenset[Capability]:
        return HOLDINGS_CAPABILITIES

    def check(self) -> ProviderHealth:
        """Always available, and always says the numbers are invented."""
        positions = sum(len(rows) for rows in self._holdings.values())
        return ProviderHealth(
            name=self.name,
            available=True,
            capabilities=self.capabilities(),
            detail=(
                f"{positions} fabricated positions across {len(self._holdings)} broker "
                "accounts; these are not anyone's real holdings"
            ),
        )

    # --- HoldingsProvider -----------------------------------------------

    def broker_holdings(self, account: BrokerAccountRef) -> list[BrokerHoldingRecord]:
        """The configured rows for ``account``.

        An account this fixture was not given raises rather than returning an empty list. The
        empty list is a meaningful answer here — "the user sold everything" — so a typo in a
        test's account id must not be able to impersonate it. Configure ``{account_id: []}``
        when emptiness is what you meant.
        """
        return list(self._rows_for(account))

    def broker_cash(self, account: BrokerAccountRef) -> Decimal | None:
        """The configured balance, or ``None`` for an account given no cash figure at all.

        ``None`` is not zero: it is the fixture standing in for a broker that publishes no cash,
        which the sync must leave alone rather than overwrite with a zero.
        """
        self._rows_for(account)
        return self._cash.get(account.broker_account_id)

    def _rows_for(self, account: BrokerAccountRef) -> tuple[BrokerHoldingRecord, ...]:
        try:
            return self._holdings[account.broker_account_id]
        except KeyError as exc:
            raise ProviderUnavailable(
                f"this fixture holds no answer for broker account "
                f"{account.broker_account_id}; configure it explicitly (an empty list means "
                "the account holds nothing, and must be said rather than inferred)",
                provider=self.name,
            ) from exc
