import puppeteer from "puppeteer-core";
const [base] = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new" });
const p = await b.newPage();
const errs = [];
p.on("console", m => m.type() === "error" && errs.push(m.text()));
p.on("pageerror", e => errs.push(String(e)));
await p.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 2 });
await p.goto(base + "/performance", { waitUntil: "networkidle0" });
const before = await p.$$eval("#hTable tbody tr", rs => rs.map(r => r.cells[0].textContent.trim()));
await p.click('#hTable thead th[data-k="pnl_pct"]');
const sorted = await p.$$eval("#hTable tbody tr", rs => rs.map(r => r.cells[0].textContent.trim()));
await p.type("#hSearch", "SYR");
const searched = await p.$$eval("#hTable tbody tr:not([hidden])", rs => rs.length);
await p.$eval("#hSearch", el => { el.value = ""; el.dispatchEvent(new Event("input")); });
await p.select("#hFilter", "lose");
const losing = await p.$$eval("#hTable tbody tr:not([hidden])", rs => rs.map(r => r.cells[0].textContent.trim()));
console.log("  rows                :", before.length);
console.log("  first by value      :", before.slice(0, 3).join(", "));
console.log("  first by P&L% (desc):", sorted.slice(0, 3).join(", "));
console.log("  search 'SYR' shows  :", searched);
console.log("  filter 'at a loss'  :", losing.join(", ") || "(none)");
console.log("  console errors      :", errs.length ? errs : "none");
await b.close();
