"""index_member_daily.source — observed vs reconstructed membership.

An addition to docs/04's DDL that docs/09 §Backfill requires by name: "where unavailable pre-2018,
reconstruct from the earliest available file and record the reconstruction in
`index_member_daily.source` so backtests can exclude uncertain periods".

Existing rows default to 'nse_file'; the column is NOT NULL with a server default so the migration
does not need a backfill pass.


Revision ID: 0004_index_member_source
Revises: 0003_unique_pipeline_run_step
Create Date: 2026-08-20 05:41:59.249463
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_index_member_source"
down_revision: str | None = "0003_unique_pipeline_run_step"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "index_member_daily",
        sa.Column("source", sa.String(), server_default="nse_file", nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_index_member_daily_index_member_source"),
        "index_member_daily",
        "source IN ('nse_file', 'reconstructed', 'derived')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_index_member_daily_index_member_source"), "index_member_daily", type_="check"
    )
    op.drop_column("index_member_daily", "source")
    # ### end Alembic commands ###
